---
title: Sense HAT music player
hero_image: images/banner.png
description: Build a sparkling MP3 player with Scratch and the Sense HAT
version: 4
listed: true
copyedit: true
last_tested: '2018-05-29'
steps:
- title: What you will make
- title: Make it sparkle
- title: Play some tunes
  completion:
  - engaged
- title: Display the track number
- title: Change the volume
- title: Change the track
  completion:
  - internal
- title: Challenge
  completion:
  - external
- title: What can you do now?